language: go

go:
  - "1.x"

notifications:
  email:
    on_success: never
    on_failure: change

sudo: false

env:
  - GO111MODULE=on

before_install:
  # Install linters and misspell
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.15.0
  - golangci-lint --version

install:
  - echo "TRAVIS_GO_VERSION=$TRAVIS_GO_VERSION"
  - go mod download
